# -*- coding: utf-8 -*-
"""null_parquet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iYTnpT0Fg28AxB_EYVvShzOO9ly_nlGr
"""

import numpy as np
import csv
import pandas as pd
import random as rand
import pandas as pd
import pyarrow.parquet as pq
import pyarrow as pa
from datetime import datetime, timedelta
import string



'''This code block creates a CSV file with num_rows number of rows'''

num_rows=20
with open("null.csv","w",newline="") as file:
  writer = csv.writer(file)
  # writer.writerow(["Time","float32","float64","int16","int32","string","bool"])
  writer.writerow(["Null0","Null1","Null2","Null3","Null4","Null5","Null6","Null7","Null8","Null9"])


  for i in range(num_rows):
 
    writer.writerow([0,\
                     0,\
                     0,\
                    0,\
                    0,\
                         0,\
                     0,\
                     0,\
                     0,\
                     0 
    ])

'''write_parquet_file creates a parquet File with name in the write_table function'''

# read csv into pandas dataframe and write dataframe to parquet1.parquet
def write_parquet_file():
    # custom_date_parser = lambda x: datetime.strptime(x,"%YYYY-%mm-%ddT%HH:%MM:%SS")
    # default date_parser is of format 2019-01-03T00:02:11
    df = pd.read_csv('./null.csv',)#,date_parser=custom_date_parser)
    for i in range(10):
      df["Null"+str(i)]=df["Null"+str(i)].astype("object")
        # df.to_parquet('./parquetfile.parquet')
        # pa.int64() exists
    fields = [
                pa.field("Null0",pa.null()),
                pa.field("Null1",pa.null()),
                pa.field("Null2",pa.null()),
                pa.field("Null3",pa.null()),
              
                pa.field("Null4",pa.null()),
                pa.field("Null5",pa.null()),
                pa.field("Null6",pa.null()),
                pa.field("Null7",pa.null()),
                pa.field("Null8",pa.null()),
                pa.field("Null9",pa.null()),
    ]
    my_schema = pa.schema(fields)

    table1 = pa.Table.from_pandas(df, schema=my_schema, preserve_index=False)
 

    # table1 = pa.Table.from_pandas(df)
    pq.write_table(table1, 'null.parquet',coerce_timestamps="ms")

write_parquet_file()

'''reads the parquet file into a pandas dataframe and prints it along with its schema.
'''
def read_parquet_file():
  pfile = pq.read_table(source="./null.parquet")
  return pfile.to_pandas(),"Schema: {}".format(pfile.schema)

read_parquet_file()

# Alternative method for later
# def write_parquet_file2():
#   df.to_parquet('./anotherparquetfile.parquet',use_deprecated_int96_timestamps=True)